# Generated by Django 3.2.4 on 2021-06-29 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpayments',
            name='bankname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='branchname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='chequedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='chequeno',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='reference',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='type',
            field=models.CharField(choices=[('paytm', 'paytm'), ('gpay', 'gpay'), ('cash', 'cash'), ('card', 'card'), ('cash', 'cash')], default='cash', max_length=30),
        ),
    ]
