# Generated by Django 3.2.4 on 2021-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpayment', '0002_auto_20210629_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpayments',
            name='chequeno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpayments',
            name='type',
            field=models.CharField(choices=[('paytm', 'paytm'), ('gpay', 'gpay'), ('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=30),
        ),
    ]
