# Generated by Django 3.2.4 on 2021-06-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'phone number must be 10 digit')]),
        ),
    ]
