# Generated by Django 3.2.4 on 2021-06-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='diesel_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater then 0')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='petrol_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater then 0')]),
        ),
    ]
