# Generated by Django 3.2.4 on 2021-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('block', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('education', models.CharField(max_length=30)),
                ('dateofjoin', models.DateField()),
                ('shifttime', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Night', 'Night')], max_length=10)),
                ('workinghours', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('bankname', models.CharField(max_length=30)),
                ('bankaccountno', models.IntegerField()),
                ('IFSCcode', models.IntegerField()),
                ('panno', models.IntegerField()),
                ('aadharno', models.IntegerField()),
                ('reference', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('document', models.FileField(upload_to='documents')),
            ],
        ),
    ]
