# Generated by Django 3.2.4 on 2021-06-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0002_auto_20210621_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='accountno',
            new_name='bankaccountno',
        ),
    ]
