# Generated by Django 3.2.4 on 2021-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntransaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntransaction',
            name='creditor_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ntransaction',
            name='closingtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ntransaction',
            name='openingtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
