# Generated by Django 3.2.4 on 2021-07-01 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_master', '0004_auto_20210628_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_paydetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('type', models.CharField(choices=[('paytm', 'paytm'), ('gpay', 'gpay'), ('cash', 'cash'), ('bank', 'bank')], default='cash', max_length=30)),
                ('cheque_no', models.IntegerField()),
                ('cheque_date', models.DateField()),
                ('bankname', models.CharField(max_length=30)),
                ('branchname', models.CharField(max_length=20)),
                ('account_no', models.IntegerField()),
                ('IFSCcode', models.IntegerField()),
                ('final_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('reference', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')])),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='employee_master.employee')),
            ],
        ),
    ]
