# Generated by Django 3.2.4 on 2021-06-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_auto_20210624_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_master',
            name='lostdieselprice',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='tank_master',
            name='lostpetrolprice',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value must be greater than 0')]),
        ),
    ]
